plugins {
    id 'java-library'
    id 'jacoco'
    id 'com.diffplug.spotless'
    id 'net.ltgt.errorprone'
    id 'net.ltgt.nullaway'
    id 'io.freefair.lombok'
}

group = 'com.github.abashev'

repositories {
    mavenCentral()
}

testing {
    suites {
        test {
            useJUnitJupiter()
        }
    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

// Integration test source set
sourceSets {
    integrationTest {
        java.srcDir 'src/integrationTest/java'
        resources.srcDir 'src/integrationTest/resources'
        compileClasspath += sourceSets.main.output + sourceSets.test.output
        runtimeClasspath += sourceSets.main.output + sourceSets.test.output
    }
}

configurations {
    integrationTestImplementation.extendsFrom testImplementation
    integrationTestRuntimeOnly.extendsFrom testRuntimeOnly
}

tasks.register('integrationTest', Test) {
    group = 'verification'
    description = 'Runs integration tests.'
    testClassesDirs = sourceSets.integrationTest.output.classesDirs
    classpath = sourceSets.integrationTest.runtimeClasspath
    useJUnitPlatform()
    shouldRunAfter(tasks.test)
}

// JaCoCo
jacocoTestReport {
    dependsOn test

    reports {
        xml.required = true
        html.required = false
    }
}

// Spotless
spotless {
    java {
        palantirJavaFormat('2.89.0')
    }
}

// Error Prone + NullAway
dependencies {
    errorprone libs.errorprone.core
    errorprone libs.nullaway
}

nullaway {
    annotatedPackages.add('com.github.vfss3')
}
