pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
}

dependencyResolutionManagement {
    repositories {
        mavenCentral()

        maven {
            url = 'https://jitpack.io'
        }
    }
}

rootProject.name = 'vfs-s3'

include 'commons-vfs'
include 'jdk'
include 'spring-6'
