pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
}

dependencyResolutionManagement {
    repositories {
        mavenCentral()

        maven {
            url = 'https://jitpack.io'
        }
    }
}

rootProject.name = 'vfs-s3'

include ':modules:commons-vfs'
include ':modules:jdk'
include ':modules:spring-6'
include ':modules:spring-7'
