[versions]
commons-vfs2 = "2.10.0"
aws-sdk-v2 = "2.47.1"
junit-jupiter = "6.1.1"
commons-io = "2.22.0"
logback = "1.5.37"
slf4j = "2.0.18"
assertj = "3.27.7"
testcontainers = "1.19.8"
jackson = "2.15.4"
palantir-java-format = "2.89.0"
errorprone = "2.42.0"
nullaway = "0.13.7"
error-prone-support = "0.26.0"
spring = "6.2.4"

[libraries]
commons-vfs2 = { module = "org.apache.commons:commons-vfs2", version.ref = "commons-vfs2" }
aws-sdk-s3 = { module = "software.amazon.awssdk:s3", version.ref = "aws-sdk-v2" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
junit-platform-suite = { module = "org.junit.platform:junit-platform-suite", version.ref = "junit-jupiter" }
commons-io = { module = "commons-io:commons-io", version.ref = "commons-io" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
jcl-over-slf4j = { module = "org.slf4j:jcl-over-slf4j", version.ref = "slf4j" }
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj" }
testcontainers-core = { module = "org.testcontainers:testcontainers", version.ref = "testcontainers" }
testcontainers-localstack = { module = "org.testcontainers:localstack", version.ref = "testcontainers" }
testcontainers-junit-jupiter = { module = "org.testcontainers:junit-jupiter", version.ref = "testcontainers" }
errorprone-core = { module = "com.google.errorprone:error_prone_core", version.ref = "errorprone" }
nullaway = { module = "com.uber.nullaway:nullaway", version.ref = "nullaway" }
error-prone-support-contrib = { module = "tech.picnic.error-prone-support:error-prone-contrib", version.ref = "error-prone-support" }
spring-core = { module = "org.springframework:spring-core", version.ref = "spring" }
spring-context = { module = "org.springframework:spring-context", version.ref = "spring" }
