[versions]
commons-vfs2 = "2.9.0"
aws-sdk-s3 = "1.12.797"
junit-jupiter = "6.0.3"
commons-io = "2.22.0"
logback = "1.5.32"
slf4j = "2.0.17"
assertj = "3.27.7"
testcontainers = "1.19.8"
jackson = "2.15.4"
palantir-java-format = "2.89.0"
errorprone = "2.42.0"
nullaway = "0.13.4"
spring = "6.2.4"
spring7 = "7.0.6"

[libraries]
commons-vfs2 = { module = "org.apache.commons:commons-vfs2", version.ref = "commons-vfs2" }
aws-sdk-s3 = { module = "com.amazonaws:aws-java-sdk-s3", version.ref = "aws-sdk-s3" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
commons-io = { module = "commons-io:commons-io", version.ref = "commons-io" }
commons-httpclient = { module = "commons-httpclient:commons-httpclient", version = "3.1" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
jcl-over-slf4j = { module = "org.slf4j:jcl-over-slf4j", version.ref = "slf4j" }
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj" }
testcontainers-core = { module = "org.testcontainers:testcontainers", version.ref = "testcontainers" }
testcontainers-localstack = { module = "org.testcontainers:localstack", version.ref = "testcontainers" }
testcontainers-junit-jupiter = { module = "org.testcontainers:junit-jupiter", version.ref = "testcontainers" }
errorprone-core = { module = "com.google.errorprone:error_prone_core", version.ref = "errorprone" }
nullaway = { module = "com.uber.nullaway:nullaway", version.ref = "nullaway" }
spring-core = { module = "org.springframework:spring-core", version.ref = "spring" }
spring-context = { module = "org.springframework:spring-context", version.ref = "spring" }
spring7-core = { module = "org.springframework:spring-core", version.ref = "spring7" }
spring7-context = { module = "org.springframework:spring-context", version.ref = "spring7" }

[plugins]
shadow = { id = "com.gradleup.shadow", version = "9.4.1" }
nexus-publish = { id = "io.github.gradle-nexus.publish-plugin", version = "2.0.0" }
