name: Build with integration tests and code coverage

on:
  push:
    branches: [ '17.0' ]

permissions:
  checks: write
  pull-requests: write
  repository-projects: write
  contents: write

jobs:
  full-build:
    strategy:
      matrix:
        environment: [ AWS-1, YANDEX-1, YANDEX-2 ]
        java-version: [ 17 ]
    environment: ${{ matrix.environment }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'liberica'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B verify jacoco:report
        env:
          BASE_URL: ${{ vars.BASE_URL }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}

      - name: Publish Test Report
        uses: dorny/test-reporter@v2
        if: ${{ !cancelled() }}
        with:
          name: Test Results
          path: '**/target/surefire-reports/junitreports/*.xml'
          reporter: java-junit

      - name: Jacoco Report to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.7.2
        with:
          paths: ${{ github.workspace }}/target/site/jacoco/jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 40
          min-coverage-changed-files: 60
          title: Code Coverage
          comment-type: summary

      - name: Fail PR if overall coverage is less than 80%
        if: ${{ steps.jacoco.outputs.coverage-overall < 80.0 }}
        uses: actions/github-script@v8
        with:
          script: |
            core.setFailed('Overall coverage is less than 80%!')