name: Build with integration tests and code coverage

on:
  push:
    branches: [ '17.0' ]
  pull_request:
    branches: [ '17.0' ]

permissions:
  checks: write
  pull-requests: write
  repository-projects: write
  contents: write

jobs:
  build:
    #    strategy:
    #      matrix:
    #        environment: [ AWS-1, YANDEX-1, YANDEX-2 ]
    #        java-version: [ 17 ]
    #    environment: ${{ matrix.environment }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: 17
          distribution: 'liberica'
          cache: 'gradle'

      - name: Build with Gradle
        run: ./gradlew check integrationTest jacocoTestReport

      - name: Publish Test Report
        uses: dorny/test-reporter@v2
        if: ${{ !cancelled() }}
        with:
          name: Test Results
          path: '**/build/test-results/**/*.xml'
          reporter: java-junit
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Jacoco Report to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.7.2
        with:
          paths: >-
            ${{ github.workspace }}/commons-vfs/build/reports/jacoco/test/jacocoTestReport.xml,
            ${{ github.workspace }}/jdk/build/reports/jacoco/test/jacocoTestReport.xml,
            ${{ github.workspace }}/spring-6/build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 40
          min-coverage-changed-files: 60
          title: Code Coverage
          comment-type: summary
          update-comment: true

#      - name: Fail PR if overall coverage is less than 80%
#        if: ${{ steps.jacoco.outputs.coverage-overall < 80.0 }}
#        uses: actions/github-script@v8
#        with:
#          script: |
#            core.setFailed('Overall coverage is less than 80%!')