name: Submit dependency graph

on:
  push:
    branches: [ '17.0' ]

permissions:
  contents: write

jobs:
  full-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: 17
          distribution: 'liberica'

      - name: Submit Dependency Snapshot
        uses: gradle/actions/dependency-submission@v5
