name: Submit dependency graph

on:
  push:
    branches: [ branch-4.x.x ]

permissions:
  contents: write

jobs:
  full-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Submit Dependency Snapshot
      uses: advanced-security/maven-dependency-submission-action@v3
