name: Submit dependency graph

on:
  push:
    branches: [ '17.0' ]

permissions:
  contents: write

jobs:
  full-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Submit Dependency Snapshot
        uses: advanced-security/maven-dependency-submission-action@v5
