name: Build pull request with simple check

on:
  pull_request:
    branches: [ 17.0 ]

permissions:
  checks: write
  pull-requests: write
  repository-projects: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: 17
          distribution: 'liberica'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B verify jacoco:report

      - name: Publish Test Report
        uses: dorny/test-reporter@v2
        if: ${{ !cancelled() }}
        with:
          name: Test Results
          path: '**/target/surefire-reports/TEST-*.xml,**/target/failsafe-reports/TEST-*.xml'
          reporter: java-junit

      - name: Jacoco Report to PR
        uses: madrapps/jacoco-report@v1.7.2
        with:
          paths: ${{ github.workspace }}/target/site/jacoco/jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 40
          min-coverage-changed-files: 60
          title: Code Coverage
          comment-type: summary
